# Generated by Django 2.0 on 2017-12-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Name',
            new_name='name',
        ),
    ]
