# Generated by Django 2.0 on 2017-12-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
