# Generated by Django 2.0 on 2017-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171210_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
