# Generated by Django 2.0 on 2018-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_solarsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PS4', 'Playstation'), ('XB1', 'XBox'), ('PC', 'Computer')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Please add a description'),
        ),
    ]
