# Generated by Django 2.0 on 2018-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180112_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('XB1', 'XBox'), ('PS4', 'Playstation')], default='PC', max_length=3),
        ),
    ]
