# Generated by Django 2.0 on 2018-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180112_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('PS', 'Playstation'), ('XB', 'XBox')], default='PC', max_length=2),
        ),
    ]
