# Generated by Django 2.0 on 2018-01-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20180112_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('XB', 'XBox'), ('PS', 'Playstation'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
    ]
