# Generated by Django 2.0 on 2018-01-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_lfgpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgpost',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lfgpost',
            name='players',
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('PC', 'Computer'), ('XB', 'XBox')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('PC', 'Computer'), ('XB', 'XBox')], default='PC', max_length=2),
        ),
    ]
