# Generated by Django 2.0 on 2018-01-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20180115_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgpost',
            name='group_size',
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='commander',
            field=models.CharField(default='doughboy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('XB', 'XBox'), ('PS', 'Playstation'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('XB', 'XBox'), ('PS', 'Playstation'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
    ]
