# Generated by Django 2.0 on 2018-01-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20180116_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgpost',
            name='activity',
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('XB', 'XBox'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('XB', 'XBox'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
    ]
