# Generated by Django 2.0 on 2018-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20180116_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('XB', 'XBox'), ('PS', 'Playstation')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('XB', 'XBox'), ('PS', 'Playstation')], default='PC', max_length=2),
        ),
    ]
