# Generated by Django 2.0 on 2018-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20180116_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='rank',
            field=models.CharField(default='harmless', max_length=200),
        ),
        migrations.AddField(
            model_name='lfgpost',
            name='ship',
            field=models.CharField(default='sidewinder', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('XB', 'XBox'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('PS', 'Playstation'), ('XB', 'XBox'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
    ]
