# Generated by Django 2.0 on 2018-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20180117_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='message',
            field=models.TextField(default='looking for wing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('PS', 'Playstation'), ('XB', 'XBox')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='discord_link',
            field=models.URLField(blank=True, default='Not Given', null=True),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='location',
            field=models.CharField(default='Not Given', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('PC', 'Computer'), ('PS', 'Playstation'), ('XB', 'XBox')], default='PC', max_length=2),
        ),
    ]
