# Generated by Django 2.0 on 2018-01-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20180118_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('XB', 'XBox'), ('PS', 'Playstation'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lfgpost',
            name='platform',
            field=models.CharField(choices=[('XB', 'XBox'), ('PS', 'Playstation'), ('PC', 'Computer')], default='PC', max_length=2),
        ),
    ]
